#!/bin/bash -eE
#
##############################################################################
##  This software may be modified and distributed under the terms
##  of the MIT license.  See the LICENSE file for details.
##
##  Unless required by applicable law or agreed to in writing,
##  software distributed under the License is distributed on an
##  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
##  KIND, either express or implied.  See the License for the
##  specific language governing permissions and limitations
##  under the License.
##
##  Copyright (c) 2021 Amelia Sara Greene <barelyaprincess@gmail.com>
##  Copyright (c) 2021 Penoaks Publishing LLC <development@penoaks.com>
##
##  Linstrap: Linux OS Bootstrapping and Launcher for UN*X
##############################################################################
#
# This is the entrypoint for the entire Linstrap setup utility.

LC_ALL=${LC_ALL:-en_US.utf-8}

APP_ROOT="${APP_ROOT:-$(dirname "$0" | xargs realpath)}"
if [ ! -d "${APP_ROOT}"; then
  echo "Something went wrong and directories appear to be missing! {APP_ROOT=${APP_ROOT}}"
  exit 1
fi

if [ -d "${APP_ROOT}/javabox" ] || [ ! -f "${APP_ROOT}/.initalized" ]; then
    # For the time being we're using a full chroot enrivonment.
    # But frankly, this could be made tremendouly smaller to safe time.
    debootstrap --variant minbase --components=main,contrib,non-free stable "${APP_ROOT}/javabox"

    echo -en "APT::Install-Recommends \"0\";\nAPT::Install-Suggests \"0\";" > "${APP_ROOT}/javabox/etc/apt/apt.conf.d/30-norecommends-nosuggests"

    chroot "${APP_ROOT}/javabox" /bin/bash -C "apt update && apt install default-jdk groovy"

    echo "VERSION=\"2021.08-$(git rev-parse --short --verify HEAD 2>/dev/null)\"" > "${APP_ROOT}/.initalized"
fi

alias ll="ls -la"

linux64 env -i -S USER=root HOME=/root TERM=xterm-256color LOGNAME=root LANG=C.UTF-8 XDF_RUNTIME_DIR=/ PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" /usr/bin/unshare --mount --mount-proc --root="${APP_ROOT}/javabox" bash
