#!/bin/bash -e
[ $LINSTRAP_BUILD_ROOT ] || exit 1

addMenuOption "Chroot into Root System" "rootSystemChroot"

exec_root () {
    mount  -t proc proc ${LINSTRAP_BUILD_ROOT}/proc
    mount  -t sysfs sysfs ${LINSTRAP_BUILD_ROOT}/sys

    chroot "$LINSTRAP_BUILD_ROOT" $*

    umount ${LINSTRAP_BUILD_ROOT}/proc
    umount ${LINSTRAP_BUILD_ROOT}/sys
}

rootSystemChroot() {
    echo "Entering the chroot environment. Use 'exit' to return to the host."
    echo

    exec_root /bin/env -i \
        HOME=/root \
        TERM="$TERM" \
        PS1='(chroot) \u:\w\$ ' \
        PATH=/bin:/usr/bin:/sbin:/usr/sbin \
        /bin/bash --login +h
}
