#!/bin/bash -e
[ $LINSTRAP_BUILD_ROOT ] || exit 1

mkdir -pv "${LINSTRAP_BUILD_ROOT}/etc/apt" 2>/dev/null

case <<EOF > "${LINSTRAP_BUILD_ROOT}/etc/apt/source.list"
deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu focal-security main restricted universe multiverse
EOF

echo "APT::Install-Recommends \"false\";" > ${LINSTRAP_BUILD_ROOT}/etc/apt/apt.conf.d/99-norecommends
echo "APT::Install-Suggests \"false\";" > ${LINSTRAP_BUILD_ROOT}/etc/apt/apt.conf.d/99-nosuggests