#!/bin/bash -e
[ LINSTRAP_HOME ] || exit 1

addMenuOption "Factory Reset" "clean"

clean() {
	echo "Dangerous!!!"
	exit 0

	## TODO Improve

	echo -n "Clearing Work Directory..."
	rm -r ${LINSTRAP_HOME}/workdir
	echo "done!"

	echo -n "Deleting Debootstrap Binary"
	rm -r ${LINSTRAP_HOME}/data/${PROJECT}
	echo "done!"
}
